---
format: revealjs
---


## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**II. Writing a Convincing Argument**

- Brainstorming premises
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Check Canvas submissions

2. Open news web pages for prompts to discuss
    - CNN, NYT, Washington Post, The Guardian, Irish Times, etc.
    
:::



## Fuse 101: Our Most Important Goal! {background-image="Images/background-news_v2.png" .center}

<br>

**Our primary goal is to ensure everyone in this room connects to the Drury experience in meaningful ways.**

- Finding and connecting to communities on campus

- Finding a major and a great advisor

- Navigating the Drury bureaucracy

- Planning your four years at Drury

- Scheduling

::: notes

**Life Check-in: Everybody doing ok?**

<br>

**Anybody run into anything we can help with?**

:::



## What's happening in the news? Any big stories to discuss? {background-image="Images/background-news_v2.png" .center}

::: notes

*Open news web pages for prompts to discuss*

- CNN, NYT, Washington Post, The Guardian, Irish Times, etc.

<br>

**So, what's going on in the world since we met last week?**

- **What big stories are you following / interested in? why?**

<br>

**Anything here in town or on our campus we should be keyed in to?**
:::



## Paper 1 Prompt {background-image="Images/background-news_v2.png" .center}

<br>

### What was the the single most important "current" event of the last 18 years (e.g. your lifetime) WITHIN the borders of the United States?

::: notes

Here is the paper prompt you are all working on.

<br>

Last class we road-tested your ideas as elevator pitches to get them on their feet and to help you reflect on your choices

<br>

For today I asked you to brainstorm 10 possible reasons that support your argument

- e.g. possible premises for an argument paper.

<br>

**How did that go? Did 10 feel like a lot? Too many?**

<br>

SLIDE: Let's talk about what makes a "good" premise in an argument

:::



## A "good" premise is: {background-image="Images/background-news_v2.png" .center}

:::: {.incremental}

::: {.r-fit-text}
1. clear, 

2. a complete idea, 

3. logically connected to the conclusion, and 

4. could be supported by evidence.
:::
::::

::: notes

**REVEAL each**

- Clear: Keep it simple!

- Complete: A complete sentence

- Logic: Don't forget you are building a strong inductive argument

- Evidence: If no evidence exists to support this idea it will be much harder to sell it to the reader

<br>

**Everybody have these written down?**

<br>

**Any questions on them?**

<br>

Let's apply this to your brainstormed list

:::



## Brainstorming your Argument {background-image="Images/background-news_v2.png" .center}

<br>

On a blank piece of paper write your thesis statement across the top:

"X is the most important US-based current event of the last 18 years."

::: notes


:::



## Brainstorming your Argument {background-image="Images/background-news_v2.png" .center}

<br>

Add your brainstormed list of **10 reasons** you chose this case

- Make sure each reason is a "good" premise!

::: notes

Go!

<br>

Now, everybody stand up!

- Your job is to review everyone else's lists of reasons.

<br>

I want you to put a check mark next to the strongest premises on their lists

- Let's go!

<br>

Ok, go take a look at your list.

- Any surprises for you?

- Did everybody flag the premises you thought they would?

:::



## Paper 1 Prompt {background-image="Images/background-news_v2.png" .center}

<br>

### What was the the single most important "current" event of the last 18 years (e.g. your lifetime) WITHIN the borders of the United States?

::: notes

First, let's talk about what you got from reading other people's lists.

<br>

**In what specific ways does reading a bunch of arguments in development help us design our own?**

- **Did you identify any compelling ideas worth stealing?**

- **No names, but did you identify any types of reason that really didn't work for you? e.g. styles, approaches, structures?**

<br>

**OK, what do we do with this feedback? How do we process the evidence you just received?**

- **In other words, should you follow the checks or not?**

<br>

**What do you do if one of the reasons you really think is key didn't get many checks?**
- (Don't give up on it; Revise, clarify, try explaining it differently)

<br>

**Any questions on what we're looking for in a strong premise?**

:::




## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

1. Farrell, H. (2010, February 16). Good Writing in Political Science: An Undergraduate Student’s Short Illustrated Primer.

2. Reflect on the feedback and select the 3-5 strongest reasons for your argument diagram.

::: notes

1. Read the Farrell article for good advice on structuring an argument paper.

- Don't worry about the political science part, this is generally applicable advice for an argument paper.

2. Select the 3-5 best reasons for your argument diagram.

<br>

**Questions?**

:::