---
format: revealjs
---


## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**I. Developing our Skills Toolbox**

- Review and analyze the submitted arguments
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
F:  (ASSIGNMENT - Review all submitted arguments) FA21 2.3 - Split class into groups and have them reflect on the submitted diagrams in order to discuss 1) what makes a "good" premise? and 2) how does the class define "importance" for a current event? Groups have until next Wed (no school Mon) to find evidence for their premises

Prep for Class

1. Check Canvas submissions

2. Prep new discussion board

3. Open news web pages for prompts to discuss
    - CNN, NYT, Washington Post, The Guardian, Irish Times, etc.

<br>

Life Check-in

EVERYBODY DOING OK?

TIPS TO SHARE?

NEED ANYTHING FROM THE CLASS?

<br>

Current Events Check-in

SO, WHAT'S GOING IN THE WORLD? ANY BIG BREAKING NEWS?
:::



## For Today {background-image="Images/background-blue_triangles_flipped.png" .center}

Review, and reflect on, all the argument diagrams shared by the class. 

Use this as an opportunity to:

+ think about the exercise of diagramming an argument, 
+ the elements of "good" premises, and 
+ to identify any similarities across the arguments in our class.

::: notes

Discuss argument diagramming exercise
- Review, and reflect on, all the argument diagrams shared by the class.

Let's start just by talking about premises.

1. GIVE ME AN EXAMPLE OF A PREMISE SOMEONE SUBMITTED THAT YOU THOUGHT WAS REALLY EFFECTIVE. NOT THE WHOLE ARGUMENT, JUST A SINGLE PREMISE.



2. SO, WHAT MAKES A "GOOD" VS A "WEAK" PREMISE?



3. WHICH OF THE COMPLETE ARGUMENT DIAGRAMS STOOD OUT TO YOU AS MOST CONVINCING?
- SOMEBODY WHO WROTE CLEARLY AND CONVINCINGLY?



4. SO, WHAT IS OUR BEST ADVICE FOR OUTLINING A CONVINCING ARGUMENT?

- MINIMUM NUMBER OF PREMISES NEEDED?



Form groups of 4 (5 groups), try to work with people you've never worked with before!

First job for this group is to help us define "important current events" as represented by all of the cases our class has chosen so far.

:::



## Define "Important Current Events" {background-image="Images/background-gentle_lines_v3.png" .center}

Based on our cases and arguments, important current events have the following characteristics...

::: notes

Based on our cases and arguments, important current events have the following characteristics...

In other words, I want you to review and analyze the submissions in our forum in order to make a list of all the characteristics that make a current event "important."

QUESTIONS ON THE TASK?

Get to work!




Groups give us characteristics from your list.

* ON BOARD, consolidate lists and discuss *

* define important: of great significance or value; likely to have a profound effect on success, survival, or well-being. *




OK, DOES THIS LIST REPRESENT A "GOOD" DEFINITION OF IMPORTANT CURRENT EVENTS? WHY OR WHY NOT?



WHAT DO WE LEARN ABOUT OUR CLASS BASED ON THE CASES WE CHOSE AND THE REASONS WE PROVIDED?



:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

::: {.incremental}

1. Group selects **one argument** and agrees on the premises (3 minimum)

2. Each member of the group must bring to class **one piece of "high quality" evidence for each premise**

3. Submit your evidence (APA format) **before** class Wednesday

:::

::: notes

No class Monday so let's talk about your task for next Wednesday!

Everybody check the syllabus and let me know if you have questions about the prompt.

SLIDE: Group selects one argument and agrees on the premises (3 minimum)

SLIDE: Each member of the group must bring to class one piece of "high quality" evidence for each premise

SLIDE: Submit your evidence (APA format) before class Wednesday

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

1. Group selects **one argument** and agrees on the premises (3 minimum)

2. Each member of the group must bring to class **one piece of "high quality" evidence for each premise**

3. Submit your evidence (APA format) **before** class Wednesday

**Notes**

- See Engle (2018) and Kovach \& Rosenstiel (2011) chapter 3 for advice on high quality evidence

::: notes

SLIDE: Readings for Wednesday will help you think critically about evidence quality.

QUESTIONS?

:::
