---
format: revealjs
---


## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**II. Writing a Convincing Argument Paper**

- Reviewing and revising paper outlines
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Check Canvas submissions

2. Open news web pages for prompts to discuss
    - CNN, NYT, Washington Post, The Guardian, Irish Times, etc.
    
:::


## Fuse 101: Our Most Important Goal! {background-image="Images/background-news_v2.png" .center}

<br>

**Our primary goal is to ensure everyone in this room connects to the Drury experience in meaningful ways.**

- Finding and connecting to communities on campus

- Finding a major and a great advisor

- Navigating the Drury bureaucracy

- Planning your four years at Drury

- Scheduling

::: notes

**Life Check-in: Everybody doing ok?**

<br>

**Anybody run into anything we can help with?**

:::



## What's happening in the news? Any big stories to discuss? {background-image="Images/background-news_v2.png" .center}

::: notes

*Open news web pages for prompts to discuss*

- CNN, NYT, Washington Post, The Guardian, Irish Times, etc.

<br>

**So, what's going on in the world since we met last week?**

- **What big stories are you following / interested in? why?**

<br>

**Anything here in town or on our campus we should be keyed in to?**

<br>

SLIDE: Let's refresh our work
:::



## Paper 1 Prompt {background-image="Images/background-news_v2.png" .center}

<br>

### What was the the single most important "current" event of the last 18 years (e.g. your lifetime) WITHIN the borders of the United States?

::: notes

**Questions on the prompt for the first paper?**

<br>

Head's up that the first completed draft of the paper will be due October 4th

- We'll keep building up to it but I want to remind you of that deadline on the horizon

:::



## Farrell's (2010) Writing Advice {background-image="Images/background-news_v2.png" .center}

<br>

::: {.r-fit-text}
1. Read the Requirements for the Assignment

2. Avoid Data Dumps

3. Cut to the Chase

4. Organize, Organize, Organize

5. Exercises in Style
:::

::: notes

**Refresh my memory, how does the Farrell (2010) advice help you write this specific paper?**

- *Force discussion*

:::



## To be convincing an argument should be logical, clear, credible and critical {background-image="Images/background-news_v2.png" .center}

- **Logical**: Do the premises support the conclusion?

- **Clear**: Is the paper easy to read and understand?

- **Credible**: Is there enough high quality evidence (cited using APA)?

- **Critical**: Does the paper address weaknesses in the argument (e.g. logic, evidence, consider counter-arguments)?

::: notes
**Any questions on the rubric I use to grade your papers?**
:::




## Outlining an Argument Paper {background-image="Images/background-news_v2.png" .center}

**Intro**

- What is the question?
- Why do we care?
- Thesis statement

**Reason 1 (premise) + a clear connection to evidence**

**Reason 2 (premise) + a clear connection to evidence**

**Reason 3 (premise) + a clear connection to evidence**

::: notes

**How are we doing with our outlines?**

- **Was everybody able to connect evidence to each premise?**

<br>

Pair off, somebody new!

:::



## Review the Evidence {background-image="Images/background-news_v2.png" .center}

<br>

**Person 1: Present your evidence**

- Explain how you will use each piece and why you believe it is high quality enough for the purpose

<br>

::: {.fragment}

**Person 2: To be convincing to you...**

- Is each premise supported by enough evidence?
- Is each piece of evidence high enough quality?

:::

::: notes

Everybody repeat this exercise with a new partner!

<br>

*Check back in with the class.*

- **Anybody have questions or need advice from the group?**

:::


## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

### What do you have to have completed before our next class?

::: notes

**Check the syllabus and Canvas modules and report back!**

<br>

Exchange papers with someone else in class. 

- Your job will be to produce a counter-argument for their paper. Submit: 

1. A one-paragraph summary of their argument (in your own words), and 

2. THREE possible counter-arguments for their paper.

:::
