---
format: revealjs
---


## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**II. Writing a Convincing Argument Paper**

- Revising and resubmitting your first paper
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Open news web pages for prompts to discuss
    - CNN, NYT, Washington Post, The Guardian, Irish Times, etc.

:::



## Fuse 101: Our Most Important Goal! {background-image="Images/background-news_v2.png" .center}

<br>

**Our primary goal is to ensure everyone in this room connects to the Drury experience in meaningful ways.**

- Finding and connecting to communities on campus

- Finding a major and a great advisor

- Navigating the Drury bureaucracy

- Planning your four years at Drury

- Scheduling

::: notes

**Life Check-in: Everybody doing ok?**

<br>

**Anybody run into anything we can help with?**

:::



## What's happening in the news? Any big stories to discuss? {background-image="Images/background-news_v2.png" .center}

::: notes

*Open news web pages for prompts to discuss*

- CNN, NYT, Washington Post, The Guardian, Irish Times, etc.

<br>

**So, what's going on in the world since we met last week?**

- **What big stories are you following / interested in? why?**

:::



## Peer Evaluations {background-image="Images/background-news_v2.png" .center}

1. What are the strongest SPECIFIC aspects of the paper?

2. Score and explain your grade for each criteria in the rubric:

    - Logic: Premises support the conclusion?
    
    - Clarity: Easy to read and understand?
    
    - Credibility: Enough high quality evidence?
    
    - Critical: Addresses weaknesses in the argument?
    
**Grade Scale**: 

- Not at all (1), Somewhat (2), Mostly (3), Completely (4)

::: notes

On Monday we did peer evaluations and this morning I returned my evaluation to you

<br>

**What was an example of a useful piece of feedback you got from one of your peer reviewers?**

<br>

**How did evaluating other people's papers help you think about your own? Did it?**

<br>

**Any parts of the feedback you did not understand? Anything I can clarify?**

<br>

I'm seeing in your papers we're still struggling with the idea of a counter-argument, so let's discuss it

<br>

I want you to think about counter-arguments in the context of this paper assignment

- I'm not asking you to argue that some horrible event you selected was actually a good thing.

<br>

The key here is that the assignment asks you to argue your "horrible event" is the MOST important event of your lifetime

- The premises in your argument are, therefore, the criteria you have chosen for arguing something is most important

- Your counter-argument could very well be identifying a different event that meets those same criteria AND THEN explaining why that doesn't change your conclusion

<br>

- **Does that make sense?**

<br>

I want to practice this exercise one more time today.

- HOWEVER, the idea here is to make a CONCRETE PLAN of action!

- SLIDE

:::



## SELF Evaluations {background-image="Images/background-news_v2.png" .center}

1. What in this paper did you do well? What are you most proud of?

2. Explain your plan to strengthen your paper in **at least three specific ways**
    
    - For each, explain the problem as you understand it and how you intend to address it
    
    - Be specific!

::: notes

Self-reflection is a vital component to developing your skills as a writer.

- Doing this honestly can be difficult, but learning to honestly reflect on your own work will serve you very well in the future.

- This is your chance to honestly appraise your completed paper and to highlight the aspects you think need to be improved

<br>

Equally important to self-reflection is being action-oriented!

- Identifying a weakness is only half the job, HOW do you plan to turn this weakness into a strength?

- Research tells us that making a plan is a huge step torwards solving a problem

- So, take today's class to reflect on the peer evals, my feedback and your reading of your own paper

- DO NOT RUSH THIS EXERCISE

<br>

**Questions?**

- Get to it and then submit your evaluation for points.

:::



## Revise and Resubmit Paper 1 {background-image="Images/background-news_v2.png" .center}

<br>

Reflect on ALL of the feedback then revise and resubmit your paper for a final grade

- Due by Oct 18th

- **You MUST highlight ALL changes**

::: notes

We'll save class this Friday to work on these revisions!

:::
