---
format: revealjs
---

## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**III. It's Election Time!**

- Is our information ecosystem healthy?
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Check Canvas submissions

2. Open news web pages for prompts to discuss
    - CNN, NYT, Washington Post, The Guardian, Irish Times, etc.

:::


## Fuse 101: Our Most Important Goal! {background-image="Images/background-news_v2.png" .center}

<br>

**Our primary goal is to ensure everyone in this room connects to the Drury experience in meaningful ways.**

- Finding and connecting to communities on campus

- Finding a major and a great advisor

- Navigating the Drury bureaucracy

- Planning your four years at Drury

- Scheduling

::: notes

**Life Check-in: Everybody doing ok?**

<br>

**Anybody run into anything we can help with?**

:::



## What's happening in the news? Any big stories to discuss? {background-image="Images/background-news_v2.png" .center}

::: notes

*Open news web pages for prompts to discuss*

- CNN, NYT, Washington Post, The Guardian, Irish Times, etc.

<br>

**So, what's going on in the world since we met last week?**

- **What big stories are you following / interested in? why?**

:::



## Our semester so far... {background-image="Images/background-news_v2.png" .center}

<br>

1. Learning to navigate the college/Drury experience
2. Learning the ins and outs of seminar dynamics
3. Identifying research questions
4. Defining concepts
5. Building and evaluating logical arguments
6. Finding and evaluating evidence
7. Addressing counter-arguments
8. Practicing giving feedback to other writers

::: notes

**How are we feeling in terms of this list?**

- **Do you see your skills growing?**

<br>

**Which of these items do you personally still feel the most uncertain about?**

<br>

Don't worry, we're not done with the items on this list!

:::



## {background-image="Images/09_1-Election-2024.jpeg" .center}

::: notes

Section 3 of the class: It's election time!

- Over the next few weeks we dive deep into the current election

<br>

To kick things off this week, I want to talk about the quality of our news ecosystem

:::



## Nguyen (2019) {background-image="Images/background-news_v2.png" .center}

::: {.r-fit-text}
**The problem of living inside echo chambers**
:::

::: notes

Let's start with the Nguyen (2019).

- *Pronounciations vary depending on background, but safe to go with "when"*

<br>

**What is the conclusion of this short article?**

- (SLIDE: Therefore, the danger in our society is echo chambers, not social media bubbles.)

:::



## Nguyen (2019) {background-image="Images/background-news_v2.png" .center}

::: {.r-fit-text}
**The problem of living inside echo chambers**
:::

<br>

Therefore, the danger in our society is echo chambers, not social media bubbles.

::: notes

**How does Nguyen define a social media bubble?**

- (a belief that everybody sorts themselves into like-minded communities and hears only like-minded views.)

<br>

**How does Nguyen define an echo chamber?**

- (An echo chamber is what happens when insiders come to distrust everybody on the outside.)

<br>

SLIDE: Before we can analyze this argument we have to diagram it.

:::



## Nguyen (2019) {background-image="Images/background-news_v2.png" .center}

::: {.r-fit-text}
**The problem of living inside echo chambers**
:::

<br>

1. ?

2. ?

3. ? 

Therefore, the danger in our society is echo chambers, not social media bubbles.

::: notes
Everybody take five minutes to identify the three most important reasons Nguyen gives to support this argument.

<br>

*ON BOARD*

- **OK, what do we have?**

<br>

**SLIDE**: My version

:::


## Nguyen (2019) {background-image="Images/background-news_v2.png" .center}

- Social media echo chambers distort your ability to trust outsiders

- Echo chambers are designed to repel outside views / evidence

- This growing distrust cannot simply be solved by exposure to new ideas/groups

- The damage to our society comes from broken trust, not bubbles

Therefore, the danger in our society is echo chambers, not social media bubbles.

::: notes

**Is this a logical argument?**

- **Do the premises support the conclusion?**

<br>

Split class into small groups (3-4 each)

- Go sit with your group!

<br>

Groups, discuss what you learned from your audit of your personal news feeds

- **Does your review of your personal social media feeds indicate you live in a bubble, an echo chamber or neither?**

- **What did you learn about the health of your personal news ecosystem?**

- *PRESENT and DISCUSS*

<br>

**Groups discuss and get ready to report back: Do we agree that a diverse news diet is a "better" news diet? Why or why not?**

- *PRESENT and DISCUSS*

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

<br>

### What do you have to have completed before our next class?


::: notes

**Check the syllabus and Canvas modules and report back!**

<br>

Debating the effects of social media on society

1. Find us a piece of evidence that you argue shows social media has a positive effect on our society (APA citation and explanation), and 

2. Find us a piece of evidence that you argue shows social media has a negative effect on our society (APA citation and explanation).

<br>

**Questions?**

:::
