---
format: revealjs
---

## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**III. It's Election Time!**

- Is our information ecosystem healthy?
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
M: Do we live in echo chambers? (1. ASSIGNMENT: Using only your personal social media feeds make a list of the top “news” stories being promoted to you. Note the topic and source of each; 2. Nguyen 2019, 3. Newton 2019) see FA21 9.1


Prep for Class

1. Check Canvas submissions

2. Prep new discussion board

3. Open news web pages for prompts to discuss
    - CNN, NYT, Washington Post, The Guardian, Irish Times, etc.

<br>

LIFE CHECK-IN: EVERYBODY DOING OK? NEED ANYTHING?

<br>

Current Events Check-in

SO, WHAT'S GOING ON IN THE WORLD SINCE WE MET LAST WEEK?

- WHAT BIG STORIES ARE YOU FOLLOWING / INTERESTED IN? WHY?

- ANYTHING HERE IN TOWN OR ON OUR CAMPUS WE SHOULD BE KEYED IN TO?
:::



## Our semester so far... {background-image="Images/background-gentle_lines_v3.png" .center}

<br>

1. What is the most important current, "current" event?

2. What is the most important "current" event of your lifetime?

::: notes

So far, the first half of our semester has focused on current events as an organizing theme for the class.

This represents the "what are we talking about" portion of many of our days together.

However, in terms of skills you've done WAY more than this.

:::



## Our semester so far... {background-image="Images/background-gentle_lines_v3.png" .center}

<br>

1. Learning to navigate the college/Drury experience
2. Learning the ins and outs of seminar dynamics
3. Identifying research questions
4. Defining concepts
5. Building and evaluating logical arguments
6. Finding and evaluating evidence
7. Addressing counter-arguments
8. Practicing giving feedback to other writers

::: notes

Hot damn you have taken to this list of things quite well.

HOW ARE WE FEELING IN TERMS OF THIS LIST?

- DO YOU SEE YOUR SKILLS GROWING?

- WHICH OF THESE ITEMS DO YOU PERSONALLY STILL FEEL THE MOST UNCERTAIN ABOUT?

<br>

We're not done with this list.


:::


## {background-image="Images/09_1-Election-2024.jpeg" .center}

::: notes

Section 3 of the class: It's election time!

- Over the next few weeks we dive deep into the election

<br>

But first, this week I want to talk about the quality of our news

- ...

:::


## For Today {background-image="Images/background-blue_triangles_flipped.png" .center}

1. Canvas: Using only your personal social media feeds make a list of the top "news" stories being promoted to you. Note the topic and source of each.

2. Nguyen (2019) *The problem of living inside echo chambers*

3. Newton (2019) *How extremism came to thrive on YouTube*

::: notes

For today I gave you two short arguments to consider and asked everyone to review their social media news feeds before class.

EVERYBODY READY TO GO ON THIS?

:::



## Nguyen (2019) The problem of living inside echo chambers {background-image="Images/background-gentle_lines_v3.png" .center}

::: notes

Let's start with the Nguyen (2019).

* Pronounciations vary depending on background, but safe to go with "when" *

WHAT IS THE CONCLUSION OF THIS SHORT ARTICLE?

:::


## Nguyen (2019) The problem of living inside echo chambers {background-image="Images/background-gentle_lines_v3.png" .center}

1. ?

2. ?

3. ? 

Therefore, the divisions in our society are driven by echo chambers, not social media bubbles.

::: notes

- The divisions in our society are driven by echo chambers, not social media bubbles.


HOW DOES NGUYEN DEFINE A SOCIAL MEDIA BUBBLE?
(a belief that everybody sorts themselves into like-minded communities and hears only like-minded views.)


AND AN ECHO CHAMBER?
(An echo chamber is what happens when insiders come to distrust everybody on the outside.)



Ok, before we can analyze this argument we have to diagram it.

Everybody take five minutes to identify the three most important reasons Nguyen gives to support this argument.



* ON BOARD *

OK, WHAT DO WE HAVE?

<br>

**SLIDE**: My version

:::


## Nguyen (2019) {background-image="Images/background-gentle_lines_v3.png" .center}

- Social media echo chambers distort your ability to trust outsiders

- Echo chambers are designed to repel outside views / evidence

- This growing distrust cannot simply be solved by exposure to new ideas/groups

- The damage to our society comes from broken trust, not bubbles

Therefore, the divisions in our society are driven by echo chambers, not social media bubbles.


::: notes

IS THIS A LOGICAL ARGUMENT?



IS IT A CONVINCING ARGUMENT? WHY OR WHY NOT?



DOES YOUR REVIEW OF YOUR PERSONAL SOCIAL MEDIA FEEDS INDICATE YOU LIVE IN A BUBBLE OR AN ECHO CHAMBER?


:::



## Newton (2019) How extremism came to thrive on YouTube {background-image="Images/background-gentle_lines_v3.png" .center}

::: notes

Let's pivot this conversation to the Newton article on extremism on the internet.

SLIDE

WHAT IS THE CONCLUSION OF THIS SHORT ARTICLE?

:::


## Newton (2019) How extremism came to thrive on YouTube {background-image="Images/background-gentle_lines_v3.png" .center}

1. ?

2. ?

3. ? 

Therefore, social media companies have fostered extremist content in order to grow their profits.

::: notes

- Therefore, social media companies have fostered extremist content in order to grow their profits.



DOES NEWTOW DEFINE EXTREMISM IN THE ARTICLE?
(Not that I can see...)

CAN WE DEFINE IT FOR OURSELVES?

* Discuss *

- The holding of "extreme" views...



Before we can analyze this argument we have to diagram it.

Everybody take five minutes to identify the three most important reasons Newton gives to support this argument.



* ON BOARD *

WHAT DO WE HAVE?

<br>

**SLIDE**: My version

:::



## Newton (2019) {background-image="Images/background-gentle_lines_v3.png" .center}

- There is a ton of extremist content on these sites.

- They know it's there (Many authorities/Congress criticizes them over it)

- YouTube rewards attention generated with money despite knowing it makes the problem worse

Therefore, social media companies have fostered extremist content in order to grow their profits.

::: notes

IS THIS A LOGICAL ARGUMENT?


IS IT A CONVINCING ARGUMENT? WHY OR WHY NOT?


HOW MUCH "EXTREMIST" CONTENT DO YOU TYPICALLY SEE IN YOUR NEWS FEEDS?

:::



## For Today {background-image="Images/background-blue_triangles_flipped.png" .center}

1. Canvas: Using only your personal social media feeds make a list of the top "news" stories being promoted to you. Note the topic and source of each.

2. Nguyen (2019) *The problem of living inside echo chambers*

3. Newton (2019) *How extremism came to thrive on YouTube*

::: notes

TAKING ALL OF THIS ON BOARD, HOW CONCERNED SHOULD WE BE ABOUT THE IMPACT OF SOCIAL MEDIA ON OUR FUTURE?


DOES SOCIAL MEDIA INCREASE OR DECREASE THE LEVELS OF TRUST IN OUR SOCIETY?


HOW BIG A PROBLEM IS THIS FOR OUR FUTURE AS A DEMOCRACY?

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

Kovach & Rosenstiel (2011) ch3


