---
format: revealjs
---


## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
TBD
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
F: (Bring your major's four year plan) Set up advising sessions for next week. Discuss four year plans, finding courses on My Drury, opening your advising needs document, meeting with your major advisor, etc

<br>

Prep for Class

1. Canvas module set up for assignment?

2. Open news web pages for prompts to discuss
    - CNN, NYT, Washington Post, The Guardian, Irish Times, etc.
    
<br>

Life Check-in

EVERYBODY DOING OK?

FIRST WEEK HIGHS AND LOWS?
- CLASSES TO SWAP OUT FOR SOMETHING NEW?

NEED ANYTHING FROM THE CLASS?

<br>

2. Current Events Check-in

ANY BIG STORIES BREAKING OVER THE WEEKEND?

- ANYTHING WE SHOULD BE KEEPING OUR EYES ON?

:::


## For Today {background-image="Images/background-blue_triangles_flipped.png" .center}

Bring your major's four year plan




## TBD {background-image="Images/background-gentle_lines_v3.png" .center}

::: notes

TBD

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

Advising Sessions (II): Four year plans and spring scheduling in one-on-one meetings

1. Schedule advising session 15 mins to discuss spring schedule and 4 year plan in progress

2. Monday (Nov 4) Election Predictions time! Make a prediction for Tuesday and give us a piece of evidence that supports your hunch (no overlap in evidence!).


::: notes

TBD

:::