---
format: revealjs
---


## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**III. It's Election Time!**

- Let's talk predictions! What's going to happen on Tuesday?
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
M: Predictions time! Let's talk predictions! What's going to happen? Why do you think so? Make a prediction for Tuesday and give us a piece of evidence that supports your hunch (no overlap in evidence!). In class build arguments for each side and discuss

<br>

Prep for Class

1. Canvas module set up for assignment?

2. Open news web pages for prompts to discuss
    - CNN, NYT, Washington Post, The Guardian, Irish Times, etc.
    
<br>

Life Check-in

EVERYBODY DOING OK?

FIRST WEEK HIGHS AND LOWS?
- CLASSES TO SWAP OUT FOR SOMETHING NEW?

NEED ANYTHING FROM THE CLASS?

<br>

2. Current Events Check-in

ANY BIG STORIES BREAKING OVER THE WEEKEND?

- ANYTHING WE SHOULD BE KEEPING OUR EYES ON?

:::


## For Today {background-image="Images/background-blue_triangles_flipped.png" .center}

What does a second Biden term look like for the country and the world? Go find us evidence to evaluate this question! Get outside your bubble!




## TBD {background-image="Images/background-gentle_lines_v3.png" .center}

::: notes

TBD

:::



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

What happened?

::: notes

TBD

:::