---
format: revealjs
---


## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**IV. Paper 2 - Making a Convincing Argument**

- Getting feedback on your rough drafts
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes

Prep for Class

1. Check Canvas submissions

:::


## Fuse 101: Our Most Important Goal! {background-image="Images/background-news_v2.png" .center}

<br>

**Our primary goal is to ensure everyone in this room connects to the Drury experience in meaningful ways.**

- Finding and connecting to communities on campus

- Finding a major and a great advisor

- Navigating the Drury bureaucracy

- Planning your four years at Drury

- Scheduling

::: notes

**Life Check-in: Everybody doing ok?**

:::


## Paper 2 Prompt {background-image="Images/background-news_v2.png" .center}

### What was the the single most important "current" event of the last 18 years (e.g. your lifetime) OUTSIDE the borders of the United States?

<br>

::: {.fragment}

**A convincing argument is logical, clear, credible and critical.**

1. Where is the paper not clear enough?

2. Where is the paper not convincing enough? (e.g.evidence, counter-arguments)

:::

::: notes

Let's get into groups of three today.

- Work with new people!

<br>

I want you to spend some time focused on each paper in your group (12 mins each?)

- My advice: Don't try to rewrite their paper or advise them to write it the way you would.

- Your job, much harder, is to help them make THEIR paper better.

- Help them figure out the strongest version of their paper in their voice.

<br>

**REVEAL**

- Keep the rubric in mind, and flag these two things for them

- Go!

<br>

Group review done? Reflect on the feedback and write, write, write!

<br>

*Come back together at the end*

**Lessons so far?**

- **Things we are struggling with?**

:::



## For Next Class {background-image="Images/background-blue_triangles2.png" .center}

<br>

::: {.r-fit-text}
**Monday**

- Writing Workshop

- Completed draft due Nov 25th

:::

::: notes

Plan for Monday

<br>

**Questions on the assignment?**

:::