---
format: revealjs
---


## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**IV. Paper 2 - Making a Convincing Argument**

- Peer Evaluations
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
Prep for Class

1. Skip current events

2. Plan student pairs for evaluations

<br>

This week we ONCE AGAIN work to improve the quality of all of your papers

- Plan of attack mirrors what we did for Paper 1 in Week 8

- Peer evaluations, Self evaluations + my feedback

- You'll then have Friday in class to revise and resubmit your paper for a final grade

<br>

*Assign class into pairs*

- Your job will be to read and reflect on your partner's paper and then SUBMIT an evaluation of the paper to the person AND to me.

- This is a graded assignment you will submit to Canvas

- You will have 20 minutes to complete your evaluation

<br>

SLIDE: Let's talk details

:::



## Peer Evaluations {background-image="Images/background-news_v2.png" .center}

1. What are the strongest SPECIFIC aspects of the paper?

2. Score and explain your grade for each criteria in the rubric:

    - Logic: Premises support the conclusion?
    
    - Clarity: Easy to read and understand?
    
    - Credibility: Enough high quality evidence?
    
    - Critical: Addresses weaknesses in the argument?
    
**Grade Scale**: 

- Not at all (1), Somewhat (2), Mostly (3), Completely (4)

::: notes

Two parts to the evaluation

1. Highlight the strengths of the paper

2. REVEAL: Apply the rubric to the paper
    - Make sure to score AND explain your reasoning for each

<br>

Remember, we have two goals here

1. Give a classmate useful input to help them write a more convincing paper

2. This exercise is ultimately meant to help you reflect on your own work and to think more deeply about the elements of writing a convincing argument

<br>

**Any questions on the assignment?**

- Let's go!

- You have 20 minutes then submit this evaluation to Canvas AND email your feedback to the other person!

:::



## Peer Evaluations 2 {background-image="Images/background-news_v2.png" .center}

1. What are the strongest SPECIFIC aspects of the paper?

2. Score and explain your grade for each criteria in the rubric:

    - Logic: Premises support the conclusion?
    
    - Clarity: Easy to read and understand?
    
    - Credibility: Enough high quality evidence?
    
    - Critical: Addresses weaknesses in the argument?
    
**Grade Scale**: 

- Not at all (1), Somewhat (2), Mostly (3), Completely (4)

::: notes

*Set up new pairs and publish second assignment*

- Ok, let's do it again!

- New pairs, new evals

- You have 20 minutes then submit this evaluation to Canvas AND email your feedback to the other person!

<br>

My goal is to have everybody's paper grades and feedback done for class Wednesday

- Fingers crossed!

:::
