---
format: revealjs
---


## Today's Agenda {background-image="Images/background-news_v2.png" .center}

```{r}
# background-size="1920px 1080px"
library(tidyverse)
library(readxl)
```

<br>

::: {.r-fit-text}
**II. Writing a Convincing Argument**

- Revising and finalizing your first paper
:::

<br>

<br>

::: r-stack
Justin Leinaweaver (Fall 2024)
:::

::: notes
F: Writing Workshop to work on R&Rs (May get dropped if study skills needs another class on Wed)

Prep for Class

1. Check Canvas submissions

2. Prep new discussion board

3. Open news web pages for prompts to discuss
    - CNN, NYT, Washington Post, The Guardian, Irish Times, etc.

<br>

LIFE CHECK-IN: EVERYBODY DOING OK? NEED ANYTHING?

<br>

Current Events Check-in

SO, WHAT'S GOING ON IN THE WORLD SINCE WE MET LAST WEEK?

- WHAT BIG STORIES ARE YOU FOLLOWING / INTERESTED IN? WHY?

- ANYTHING HERE IN TOWN OR ON OUR CAMPUS WE SHOULD BE KEYED IN TO?
:::



## Revise and Resubmit Paper 1 {background-image="Images/background-gentle_lines_v3.png" .center}

Reflect on the feedback in the comments then revise and resubmit your paper for a final grade

- Submit on Canvas

- You MUST highlight ALL changes

- Due...



## For Next Class {background-image="Images/background-blue_triangles_flipped.png" .center}

1. Canvas: Using only your personal social media feeds make a list of the top "news" stories being promoted to you. Note the topic and source of each.

2. Nguyen (2019) *The problem of living inside echo chambers*

3. Newton (2019) *How extremism came to thrive on YouTube*


